### ISSUE TITLE
Not resolving relative paths breaks resolving of type definitions.

### ISSUE THREAD

**Issue by gargs0n** [KnisterPeter/typescript-patternplate-resolver#1]
Not resolving relative paths, introduced within commit [4852be4](https://github.com/KnisterPeter/typescript-patternplate-resolver/commit/4852be4), breaks the  resolving of relative type definitions. 

I have added a screenshot showing the relative import of type definitions inside the node_module styled-components@2.1.1

![styled-components-resolving](https://user-images.githubusercontent.com/859545/28779467-8b062802-7603-11e7-8213-56af3e258fd3.png)

Is there a reason why resolving of relative paths has to be forbidden?

**Comment by KnisterPeter** [comment]
It was introduced to not allow importing patterns relative without using the localname from the pattern.json
